namespace AncestorsEnhanced.Infrastructure.Tests.SystemSave;

internal static class VerifiedSystemSaveFixture
{
    private const string Base64 =
        "5Ab0YwMIAAAAT3B0aW9ucwAPAAAAU3RydWN0UHJvcGVydHkAEAMAAAAAAAAPAAAAUGFuYWNoZU9wdGlvbnMA" +
        "AAAAAAAAAAAAAAAAAAAAAAAPAAAAR3JhcGhpY09wdGlvbnMADwAAAFN0cnVjdFByb3BlcnR5ALQCAAAAAAAA" +
        "EAAAAEdyYXBoaWNzT3B0aW9ucwAAAAAAAAAAAAAAAAAAAAAAABUAAABGdWxsU2NyZWVuUmVzb2x1dGlvbgAP" +
        "AAAAU3RydWN0UHJvcGVydHkACAAAAAAAAAAJAAAASW50UG9pbnQAAAAAAAAAAAAAAAAAAAAAAAAABQAA0AIA" +
        "ABMAAABXaW5kb3dlZFJlc29sdXRpb24ADwAAAFN0cnVjdFByb3BlcnR5AAgAAAAAAAAACQAAAEludFBvaW50" +
        "AAAAAAAAAAAAAAAAAAAAAAAAkAYAABoEAAALAAAAQnJpZ2h0bmVzcwAOAAAARmxvYXRQcm9wZXJ0eQAEAAAA" +
        "AAAAAABmZoY/DQAAAFF1YWxpdHlMZXZlbAAMAAAASW50UHJvcGVydHkABAAAAAAAAAAAAgAAABMAAABTY2Fs" +
        "YWJpbGl0eVNldHRpbmcADwAAAFN0cnVjdFByb3BlcnR5AN0AAAAAAAAAEwAAAFNjYWxhYmlsaXR5U2V0dGlu" +
        "ZwAAAAAAAAAAAAAAAAAAAAAAAA8AAABQb3N0UHJvY2Vzc2luZwANAAAARW51bVByb3BlcnR5ACIAAAAAAAAA" +
        "GQAAAEVHcmFwaGljc1F1YWxpdHlTZXR0aW5ncwAAHgAAAEVHcmFwaGljc1F1YWxpdHlTZXR0aW5nczo6TE9X" +
        "AAgAAABTaGFkb3dzAA0AAABFbnVtUHJvcGVydHkAJQAAAAAAAAAZAAAARUdyYXBoaWNzUXVhbGl0eVNldHRp" +
        "bmdzAAAhAAAARUdyYXBoaWNzUXVhbGl0eVNldHRpbmdzOjpNRURJVU0ABQAAAE5vbmUADwAAAEZyYW1lUmF0" +
        "ZUxpbWl0AAwAAABJbnRQcm9wZXJ0eQAEAAAAAAAAAAADAAAAFwAAAFF1YWxpdHlTZXR0aW5nSXNDdXN0b20A" +
        "DQAAAEJvb2xQcm9wZXJ0eQAAAAAAAAAAAAEABQAAAE5vbmUABQAAAE5vbmUABQAAAE5vbmUA";

    public static byte[] Read() => Convert.FromBase64String(Base64);
}
