<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <VersionPrefix>1.0.0</VersionPrefix>
    <Authors>Elfonie</Authors>
    <Product>Ancestors Enhanced Configurator</Product>
    <Description>Portable graphics and save configurator for Ancestors: The Humankind Odyssey</Description>
  </PropertyGroup>
</Project>
